### ISSUE TITLE
Deprecated selectors

### ISSUE THREAD

**Issue by dirkdirk** [cameronbourke/yoceanic-next-syntax#5]
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

atom-text-editor, :host => atom-text-editor,atom-text-editor
...

Will this be fixed or is it something I can fix manually?

**Comment by cameronbourke** [comment]
Hey @dirkdirk, I totally missed this issue, I've stopped working on this project, however if you would like to update the selectors and send a PR I would be more than happy to review and merge. Thanks so much for the interest in the project!
