### ISSUE TITLE
UI Theme does not update

### ISSUE THREAD

**Issue by rongierlach** [cameronbourke/yoceanic-next-syntax#6]
Love the theme!

My tree / settings views don't update one I have "One Dark" selected as the UI Theme.
Anything I'm missing on my end?

**Comment by cameronbourke** [comment]
@rongierlach Hey! Sorry for the serious late reply. I've discontinued working on this project, so I'm almost certain that your issue is due to deprecated selectors I'm using in this theme. You are more than welcome to send a PR if you would like to update them. Thanks again for the interest!
